# k8s/websocket-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
  namespace: messaging-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-service
  template:
    metadata:
      labels:
        app: websocket-service
    spec:
      containers:
      - name: websocket-service
        image: your-dockerhub-username/websocket-service:latest  # Replace with your image
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: KAFKA_BROKER
          value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: messaging-app
spec:
  selector:
    app: websocket-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
